### ISSUE TITLE
The language file of zh-cn

### ISSUE THREAD

**Issue by firesahc** [Shopkeepers/Language-Files#65]
[language-zh-CN.txt](https://github.com/user-attachments/files/16330663/language-zh-CN.txt)
Built from version Shopkeepers-2.22.1，Minecraft1.16.5

**Comment by blablubbabc** [comment]
Added, thanks! (https://github.com/Shopkeepers/Language-Files/commit/ffba1398b061e13ec030c26fffb58fd1b4d023c2)
