### ISSUE TITLE
French translation file for 2.22.3

### ISSUE THREAD

**Issue by MaxxQc** [Shopkeepers/Language-Files#66]
Hello, I wasn't able to upload the file directly on GitHub.
Here is the download link for the french language file: https://www.mediafire.com/file/286ipwikfl1flj8/language-fr.yml/file
Plugin version: 2.22.3

Thanks :)

**Comment by blablubbabc** [comment]
Merci: https://github.com/Shopkeepers/Language-Files/commit/10a1bd65ff61b95736d2638bdf9d616e8b43aa6c
