### ISSUE TITLE
Adding Belarusian translation

### ISSUE THREAD

**Issue by Gazmanovich** [Shopkeepers/Language-Files#71]
[language-be.zip](https://github.com/user-attachments/files/17689133/language-be.zip)

**Comment by blablubbabc** [comment]
Added for v2.22.2+, thank you!

If you can update the translation for v2.23.1 (see https://github.com/Shopkeepers/Language-Files/compare/v2.22.2...v2.23.1#diff-5362bae55e2c64449d2ae0d0b95129da5eb035b538ea8ee62fd568a0a55aef89), this would be much appreciated.
